#
# Module manifest for module 'PSnmap'
#
# Generated by: Joakim Svendsen
#
# Generated on: 2015-08-31
#

# v1.2: Replaced all instances of [int64] with [decimal] to support x86 platforms at no cost. Sorry about that.
#       ... Except I use ToInt64(), so... yeah.
# v1.3: Code refactoring.

@{

# Script module or binary module file associated with this manifest.
#RootModule = 'PSnmap.psm1' # grrr, default with New-ModuleManifest in v4, but is not recognized in v2
ModuleToProcess = 'PSnmap.psm1' # for v2-compatibility

# Version number of this module.
ModuleVersion = '1.2'

# ID used to uniquely identify this module
GUID = '687476b1-c21e-46a0-a2c2-c7fcad73b91c'

# Author of this module
Author = 'Joakim Borger Svendsen'

# Company or vendor of this module
CompanyName = 'Svendsen Tech'

# Copyright statement for this module
Copyright = '(c) 2015-2016 Joakim Svendsen. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Linux nmap for PowerShell (almost). Ping sweeps and scans a network for specified open ports. Can also perform DNS lookups.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

